server:
  port: 8080

spring:
  cache:
    type: redis
  main:
    banner-mode: off
  ########### 数据库配置 ################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.123:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: idea
    password: 123456
  ########### redis配置 ################
  data:
    redis:
      host: 192.168.80.123
      port: 6379
      database: 1
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20  # 最大连接数，负值表示没有限制，默认8
          max-wait: -1    # 最大阻塞等待时间，负值表示没限制，默认-1
          max-idle: 8     # 最大空闲连接，默认8
          min-idle: 0     # 最小空闲连接，默认0

  ############ 配置rabbitmq #################
  rabbitmq:
    host: 192.168.80.123
    port: 5672
    username: idea
    password: 123456
    virtual-host: /

  ############ jackson 配置 ###################
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true


  ############ email 配置 ###################
  mail:
    host: smtp.163.com #发送邮件服务器
    username: jiangtdemail@163.com #发送邮件的邮箱地址
    password: VHYBYJJPFDEUOWCG #客户端授权码
    from: 系统管理员<jiangtdemail@163.com> #发送邮件的邮箱地址
    protocol: smtp # 传输协议
    default-encoding: UTF-8 # 编码方式
    properties:
      mail:
        smtp:
          port: 465 #端口号465或587
          auth: true #是否开启权限验证
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        starttls:
          enable: true # 启用STARTTLS（安全传输层协议）
  # 配置thymeleaf的相关信息
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html

############## MP 配置 #####################
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      #      logic-delete-field: isDelete #默认deleted
      #      logic-delete-value: 1
      #      logic-not-delete-value: 0
      id-type: auto
      table-prefix: t_
    banner: off
  ############# 分页插件PageHelper配置 #############
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  pageSizeZero: true


########### 日志配置 #################
#logging:
#  level:
#    root: debug
#    org:
#      springframework:
#        boot:
#          autoconfigure: ERROR

######## JWT #############
jwt:
  issuer: zs
  # 为JWT基础信息加密和解密的密钥，长度需要大于等于43
  secret: oQZSeguYloAPAmKwvKqqnifiQatxMEPNOvtwPsCLasd
  # JWT令牌的有效时间，单位秒，默认2周
  expiration: 14400

# knife4j的增强配置，不需要增强可以不配
springdoc:
  default-flat-param-object: true
  api-docs:
    # 是否开启接口文档
    enabled: true
  swagger-ui:
    # 持久化认证数据，如果设置为 true，它会保留授权数据并且不会在浏览器关闭/刷新时丢失
    persistAuthorization: true

knife4j:
  enable: true
  setting:
    language: zh_cn